name: Auto Update README

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Update Recent Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: "docs(readme): update recent activity"

      - name: Update Latest Repositories
        uses: JinoArch/github-recent-repos@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
